// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkflowAgentProgress } from "./WorkflowAgentProgress";
import type { WorkflowPhaseProgress } from "./WorkflowPhaseProgress";
import type { WorkflowRunStatus } from "./WorkflowRunStatus";

export type WorkflowRunUpdatedNotification = { threadId: string, turnId: string, callId: string, workflowName: string, workflowDescription: string, status: WorkflowRunStatus, phases: Array<WorkflowPhaseProgress>, agents: Array<WorkflowAgentProgress>, logs: Array<string>, agentCount: number, runningAgentCount: number, completedAgentCount: number, failedAgentCount: number, startedAtMs: bigint, updatedAtMs: bigint, completedAtMs: bigint | null, };
