// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkflowAgentStatus } from "./WorkflowAgentStatus";

export type WorkflowAgentProgress = { id: string, label: string, prompt: string, phase: string | null, status: WorkflowAgentStatus, startedAtMs: bigint, completedAtMs: bigint | null, error: string | null, model: string | null, agentType: string | null, };
